### PR TITLE
(#924) Support UTF-8 and fix readline

### LINKED ISSUE #924: Repl didn't do backspace correctly on multi-byte characters
@creationix 
This happened when I typed some multi-byte characters (such as chinese or japanese) and pressed backspace.

It will only delete last one byte of the character,not all of them(Unicode said they are 2 or 3 bytes)
so it will be...

```
> 中文
Length is 6
```

... and press backspace

```
> 中��
Length is 5
```

I must press backspace twice or three times to delete all bytes of a character.
The main issue is to get the actually length of each character.I think this can be fixed by adding a utf8 wrapper.
btw,this also cause the position of cursor to be wrong.

### PR DESCRIPTION
**Pull request by Miigon**
This fixed #924.
I've write a new module `ustring` to process UTF-8 strings.It has similar APIs to standard `string` module.
And with this new module,the issue was fixed.
**PS:I don't know how `lit` package management system works,but my changes may cause `readline` become depending on `ustring`.**

### CODE REVIEW

**Comment by creationix** [comment]
Yes, this will need some packaging to work with lit properly, but I can add that.

**Comment by creationix** [comment]
Does this failure look related to this PR?  It is a test for the readline module.
https://travis-ci.org/luvit/luvit/jobs/179034058#L3713-L3729

**Comment by squeek502** [comment]
Yes, the tests will need to be updated, as the current test is testing for string equality. Here's the assert that's failing:

`assert(editor.line == "a")`

Would probably need to do `assert(tostring(editor.line) == "a")` or compare against a ustring.

**Comment by creationix** [comment]
@squeek502 sounds good.  I like the tostring style.

**Comment by squeek502** [comment]
Looks like the PR currently struggles with a mixture of control sequences and characters being added at the same time.

```
    editor:onKey('a\027[Db\027[Dc\027[Dd')
```

which should be interpreted as ('a', left arrow, 'b', left arrow, 'c', left arrow, 'd') is only resulting in 'd' being added to the line.

File: deps/readline.lua [hunk 1]
```diff
@@ -396,7 +396,7 @@ local keyHandlers =
     self:getHistory(10)
   end},
   -- Printable characters
-  {{function(key, char) return char > 31 and key:sub(1,1) or nil end}, function(self, consumedKeys)
+  {{function(key, char) return char > 31 and key or nil end}, function(self, consumedKeys)
```
Comment (squeek502) [inline deps/readline.lua]: This should probably be `sub(key, 1, 1)` instead of removing the `sub` entirely. Removing the `sub` causes the entire line to get treated as printable whenever the first character is a printable character (e.g. 'a\027[D' should only consume 'a' and then interpret the rest as a left arrow key press, but without the sub, it will print the entire sequence instead).

File: deps/ustring.lua [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+end
+
+local gsub = string.gsub
+local find = string.find
+local format = string.format
+local gmatch = string.gmatch
+local match = string.match
+local lower = string.lower
+local upper = string.upper
+ustring.len = rawlen
```
Comment (squeek502) [inline deps/ustring.lua]: `rawlen` is never defined

File: deps/ustring.lua [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+
+function ustring.lower(ustr)
+    local u = ustring.copy(ustr)
+    for i = 1,#u do
+        u = lower(u)
+    end
+    return u
+end
+
+function ustring.upper()
```
Comment (squeek502) [inline deps/ustring.lua]: Missing the `ustr` param here, `ustr` is undefined in the line below

File: deps/ustring.lua (hunk 2 above)
Comment (Miigon) [inline deps/ustring.lua]: `rawlen`is lua's builtin function.
https://www.lua.org/manual/5.2/manual.html#pdf-rawlen

File: deps/readline.lua (hunk 1 above)
Comment (Miigon) [inline deps/readline.lua]: `key:sub(1,1)`suppose that the printable character is 1 byte length,but unfortunately,Lot's of unicode character isn't 1-byte-wide.This sub only gets the first byte of the character.

Maybe we need a function `chlen()` to get the length of a unicode character and the code will be like `key:sub(1,ustring.chlen(key))`

**Comment by Miigon** [comment]
Appveyor still failed,but I don't have a Windows environment to debug with.Sorry.

**Comment by squeek502** [comment]
Build is failing because `ustring` has not been added to [`package.lua`](https://github.com/luvit/luvit/blob/master/package.lua), so it's not being included when building luvit:

```
[string "bundle:deps/require.lua"]:278: No such module 'ustring' in 'bundle:/deps/readline.lua'
```

File: deps/readline.lua (hunk 1 above)
Comment (squeek502) [inline deps/readline.lua]: Since `sub` was defined as `local sub = ustring.sub`, I assumed that it would account for the unicode characters. Does `ustring.sub` not work when called on a regular string?

**Comment by Miigon** [comment]
@squeek502 So the only thing I need to do is adding it to `package.lua`,right?

**Comment by creationix** [comment]
@Miigon I believe so.  Try that.
